CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Controllers/GeneraArchivoController.cs
//@(#)CREDITOSFISCALES(W:71950:Sat.CreditosFiscales.Presentacion.Controllers:Sat.CreditosFiscales.Presentacion.Controllers.GeneraArchivoController:1:12/07/2013[Assembly:1.0:12/07/2013])

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using System.Web;
using System.Web.Mvc;
using Sat.CreditosFiscales.Procesamiento.LogicaNegocio.Servicios;
using Sat.CreditosFiscales.Presentacion.Herramientas;
using Sat.CreditosFiscales.Comunes.Entidades.AccesoLogEventos;
using Sat.CreditosFiscales.Comunes.Entidades.CodigosError;

namespace Sat.CreditosFiscales.Presentacion.Portal.Controllers
{
    public class GeneraArchivoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GeneraArchivoPdf(string folios)
        {
            try
            {
                List<string> listaDeFolios = folios.Split(',').ToList();
                byte[] archivoDeBytes = GeneraArchivoDeBytes(listaDeFolios);
                MemoryStream ms = new MemoryStream();
                ms.Write(archivoDeBytes, 0, archivoDeBytes.Length);
                ms.Position = 0;
                return File(ms, "application/pdf");
            }
            catch (ExcepcionTipificada ex)
            {
                ViewBag.OnLoadCompleteMessage = Alertas.Errror(ex.Mensaje, "Aceptar");
            }
            catch (Exception ex)
            {
                string ticket = AccesoLogEventos.EscribirEntradaLog((int)EnumErroresLineaCaptura.ErrorAlGenerarArhivo, ex);
                ExcepcionTipificada exTip = new ExcepcionTipificada("No se logró generar el archivo para las líneas de captura.", ex, ticket);
                ViewBag.OnLoadCompleteMessage = exTip.Mensaje;
            }
            return View("Blank");
        }


        private byte[] GeneraArchivoDeBytes(List<string> listaDeFolios)
        {
            using (ClienteServicioLineaCaptura servicio = new ClienteServicioLineaCaptura())
            {
                return servicio.CreateChannel().GeneraArchivos(listaDeFolios);
            }
        }
    }
}

CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Controllers/LineaCapturaController.cs
//@(#)CREDITOSFISCALES(W:71950:Sat.CreditosFiscales.Presentacion.Controllers:Sat.CreditosFiscales.Presentacion.Controllers.LineaCapturaController:1:12/07/2013[Assembly:1.0:12/07/2013])

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sat.CreditosFiscales.Presentacion.Portal.ViewModels;
using Sat.CreditosFiscales.Comunes.Entidades.Servicios;
using Sat.CreditosFiscales.Comunes.Entidades.AccesoLogEventos;
using Sat.CreditosFiscales.Presentacion.Herramientas;
using Sat.CreditosFiscales.Comunes.Entidades.CodigosError;
using Sat.CreditosFiscales.Comunes.Entidades;
using System.IO;
using Sat.CreditosFiscales.Comunes.Entidades.GeneraFormato;

namespace Sat.CreditosFiscales.Presentacion.Portal.Controllers
{
    public class LineaCapturaController : Controller
    {


        public ActionResult Index(Int64 idSolicitud = 0, bool deudorPuro = false)
        {
            GeneraLineasCapturaViewModel model = new GeneraLineasCapturaViewModel();
            model.listaLineaCaptura = new List<LineaCaptura>();
            model.deudorPuro = deudorPuro;
            string mensajeExUsuario = string.Empty;
            try
            {
                using (ClienteServicioLineaCaptura servicio = new ClienteServicioLineaCaptura())
                {
                    var usuario = new Usuario();
                     // Si solicitud proviene de la página de deudor puro obtenemos los datos del usuario
                    var usuarioApoyo = servicio.CreateChannel().ObtenerInfoUsuarioDeudorPuro(idSolicitud);
                    if (deudorPuro)
                    {
                        usuario = usuarioApoyo;
                    }
                    else
                    {
                        usuario = MemberCache.UsuarioActual;
                        usuario.IdTipoLineaMAT = usuarioApoyo.IdTipoLineaMAT;
                        usuario.IdPersonaMAT = usuarioApoyo.IdPersonaMAT;
                    }
                    var listaLineaCapturaRespuesta = servicio.CreateChannel().GenerarLineasCaptura(idSolicitud, usuario);
                    model.listaLineaCaptura = listaLineaCapturaRespuesta.LineasCaptura;
                    mensajeExUsuario = listaLineaCapturaRespuesta.Excepcion != null ? listaLineaCapturaRespuesta.Excepcion.Mensaje : string.Empty;
                }

                if (model.listaLineaCaptura.Count == 0)
                {
                    if (!string.IsNullOrEmpty(mensajeExUsuario))
                    {
                        ViewBag.OnLoadCompleteMessage = Alertas.Errror(mensajeExUsuario, "Aceptar");
                    }
                    else
                    {
                        ViewBag.OnLoadCompleteMessage = Alertas.Informacion("No hay líneas de captura para los documentos seleccionados.", "Aceptar");
                    }
                }
                else
                {

                    if (!string.IsNullOrEmpty(mensajeExUsuario))
                    {
                        ViewBag.OnLoadCompleteMessage = Alertas.Errror(mensajeExUsuario, "Aceptar");
                    }
                    else
                    {
                        //Si es solo una linea de captura generamos el pdf automaticamente
                        if (model.listaLineaCaptura.Count == 1)
                        {
                            return RedirectToAction("Index", "GeneraArchivo", new { folios = model.listaLineaCaptura[0].Folio , deudorPuro = model.deudorPuro  });
                        }
                    }

                }
            }
            catch (ExcepcionTipificada ex)
            {
                ViewBag.OnLoadCompleteMessage = Alertas.Errror(ex.Mensaje, "Aceptar");
            }
            catch (Exception ex)
            {

                string ticket = AccesoLogEventos.EscribirEntradaLog((int)EnumErroresLineaCaptura.ErrorAlGenerarLineasDeCaptura, ex);
                ExcepcionTipificada exTip = new ExcepcionTipificada("No se logró generar la línea(s) de captura.", ex, ticket);
                ViewBag.OnLoadCompleteMessage = Alertas.Errror(exTip.Mensaje, "Aceptar");

            }
            return View(model);

        }

        public ActionResult GeneraArchivo(string[] chklistaDeFolios, bool deudorPuro)
        {
            return RedirectToAction("Index", "GeneraArchivo", new { folios = string.Join(",", chklistaDeFolios), deudorPuro = deudorPuro });
        }


        public ActionResult ObtenerDocumentosAsociados(string lineaCaptura)
        {
            GenerarDocumentosDeterminanteViewModel model = new GenerarDocumentosDeterminanteViewModel();
            using (ClienteServicioLineaCaptura servicio = new ClienteServicioLineaCaptura())
            {
                model.listaDocumentosAsociados = servicio.CreateChannel().ObtenerDocumentosAsociados(lineaCaptura, MemberCache.UsuarioActual.Rfc);
            }
            return PartialView("_GridDocumentos", model);
        }
    }
}

CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Views/LineaCaptura/GeneraArchivo.cshtml
@model byte[]
@{
    Layout = null;
}
@{
    var archivopdf = "LC" + DateTime.Now.ToString("yyyyMMddHHmmss") + ".pdf";
    Response.AddHeader("content-length", Model.Length.ToString());
    Response.AddHeader("content-disposition", "attachment; filename=" + archivopdf);
    Response.ContentType = "Application/pdf";
    Response.WriteBinary(Model);
    
}

CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Views/LineaCaptura/Index.cshtml
@model Sat.CreditosFiscales.Presentacion.Portal.ViewModels.GeneraLineasCapturaViewModel
@using Sat.CreditosFiscales.Presentacion.Herramientas
@using Sat.CreditosFiscales.Presentacion.Herramientas.ExtensionsMethods


<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section encabezado
{
    <h1>Formatos para pago</h1>
}



<table>
    <tr>
        <td>
            <table id="gridLineaCaptura" class="tabla">
                <thead>
                    <tr>
                        <th style="width: 100px;">Selección de formatos<br />
                            @if (Model != null && Model.listaLineaCaptura != null)
                            {
                                if (Model.listaLineaCaptura.Count > 0)
                                {
                                <input type="checkbox" id="chkSeleccionaTodos" name="chkSeleccionaTodos" />
                                }
                            }

                        </th>
                        <th style="width: 130px;">Folio</th>
                        <th style="width: 210px;">Resolución o referencia</th>
                        <th style="width: 130px;">Fecha de generación</th>
                        <th style="width: 130px;">Vigente hasta</th>
                        <th style="width: 130px;">Importe total a pagar</th>
                        <th style="width: 60px;"></th>

                    </tr>
                </thead>
                <tbody>
                    @if (Model == null || Model.listaLineaCaptura == null)
                    {
                        <tr>
                            <td colspan="8">&nbsp;
                            </td>
                        </tr>
                    }
                    else
                    {
                        if (Model.listaLineaCaptura.Count == 0)
                        {
                        <tr>
                            <td colspan="8">No hay líneas de captura.
                            </td>
                        </tr>
                        }
                        else
                        {


                            using (Html.BeginForm("GeneraArchivo", "LineaCaptura", FormMethod.Post, new { id = "frmLineaCaptura", chklistaDeFolios = "chklistaDeFolios", OnComplete = "ocultarReloj();" }))
                            {
                        @Html.HiddenFor(m => m.deudorPuro, "deudorPuro");

                                                                        for (int i = 0; i < Model.listaLineaCaptura.Count; i++)
                                                                        {
                        <tr>
                            <td>
                                <input type="checkbox" value="@Model.listaLineaCaptura[i].Folio" name="chklistaDeFolios" onchange="Valida();"  />
                            </td>
                            <td>
                                @if (Model.listaLineaCaptura[i].Documentos.Count > 1)
                                {
                                    <a href="javascript:" onclick="VerDetalle('@Model.listaLineaCaptura[i].Linea')" >@Model.listaLineaCaptura[i].Folio</a>
                                }
                                else
                                {
                                    @Model.listaLineaCaptura[i].Folio
                                }
                            </td>
                            <td>@Model.listaLineaCaptura[i].Documentos[0].NumDocumento
                                @if (Model.listaLineaCaptura[i].Documentos.Count > 1)
                                {
                                    string.Format("{0}", "...");
                                }
                            </td>
                            <td>@Model.listaLineaCaptura[i].FechaEmision</td>
                            <td>@Model.listaLineaCaptura[i].FechaVencimiento</td>
                            <td>@Model.listaLineaCaptura[i].ImporteTotal.ToCurrency()</td>

                            <td>
                                <img src="~/Images/imagenpdf.jpg" width="35" height="35" alt="Generar pdf" style="cursor:pointer" onclick="GenerarPdf('@Model.listaLineaCaptura[i].Folio')" /></td>
                        </tr>
                                                                        }

                            }
                        }

                    }

                </tbody>
            </table>

        </td>

    </tr>
    <tr>
        <td>
            <div id="botonera">
                @{
                    var vieneDePaginaDeudorPuro = string.IsNullOrEmpty(Request.QueryString["deudorPuro"]) ? false : Convert.ToBoolean(Request.QueryString["deudorPuro"]);      
                }
                @if (vieneDePaginaDeudorPuro)
                {
                    <input type="button" value="Regresar a consulta" onclick="reloj();window.location.href='@Url.Action("DeudoresPuros", "GeneracionPrivada")    ';" />
                }
                else
                {
                    <input type="button" value="Regresar a pago total" onclick="reloj();window.location.href='@Url.Action("Index", "GeneracionPrivada", new { accion = Sat.CreditosFiscales.Comunes.Entidades.AccionesPantalla.EnumAccionGeneraFormato.PagoTotal })    ';" />
                }



                @if (Model != null && Model.listaLineaCaptura != null)
                {
                    if (Model.listaLineaCaptura.Count > 0)
                    {
                    <input type="button" id="btnGenerarDocumentos" value="Generar formatos" />
                    }
                }
            </div>
        </td>

    </tr>
</table>



<div id="modalDocumentos" title="Créditos fiscales"></div>

<div id="divArchivo"></div>



<script>

    $('#btnGenerarDocumentos').click(function (e) {
        try {

            var totalSeleccionados = $('#gridLineaCaptura :input:checkbox[name="chklistaDeFolios"]:checked').length;
            if (totalSeleccionados < 1) {
                @Alertas.Errror("Debe seleccionar al menos una línea de captura.", "Aceptar");
            } else {
                $('#frmLineaCaptura').submit();
            }
        } catch (err) {
            openDialog(err, 1, "Aceptar");
        }
    });

    $('#chkSeleccionaTodos').change(function () {
        var seleccion = this.checked;
        $('#gridLineaCaptura :input[type="checkbox"]').each(function () {
            this.checked = seleccion;
        });
    });


    function Valida() {
        var totalCheckBox = $('#gridLineaCaptura :input:checkbox[name="chklistaDeFolios"]').length;
        var totalSeleccionados = $('#gridLineaCaptura :input:checkbox[name="chklistaDeFolios"]:checked').length;
        $('#chkSeleccionaTodos').prop('checked', totalCheckBox == totalSeleccionados);
    }
    function GenerarPdf(folio) {
        $('#gridLineaCaptura :input[type="checkbox"]').each(function () {
            this.checked = false;
        });
        $('#gridLineaCaptura :input:checkbox[name="chklistaDeFolios"]').each(function () {
            var valorCheckBox = this.value;
            if (valorCheckBox == folio) {
                this.checked = true;
                $('#frmLineaCaptura').submit();
                return false;
            }
        });
    }

    function VerDetalle(lineaCaptura) {
        try {
            $('#modalDocumentos').empty();
            $('#modalDocumentos').dialog({
                autoOpen: true,
                modal: true,
                width: 320,
                height: 400,
                resizable: false,
                open: function (event, ui) {
                    var url = '@Url.Action("ObtenerDocumentosAsociados", "LineaCaptura")';
                    $(this).load(url, { lineaCaptura: lineaCaptura });
                }
            });

            } catch (err) {
                openDialog(err, 1, "Aceptar");
            }
        }



</script>

CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Views/LineaCaptura/_GridDocumentos.cshtml
@model Sat.CreditosFiscales.Presentacion.Portal.ViewModels.GenerarDocumentosDeterminanteViewModel
<div id="divContenido" style="font-size: x-small; text-align: center; overflow: auto">
    <script>
        ocultarReloj();
    </script>
    <table class="tabla">
        <thead>
            <tr>
                <th style="width:295px; height:35px;">Resolución o referencia</th>
            </tr>
        </thead>
        <tbody>
            @if (Model == null || Model.listaDocumentosAsociados == null)
            {
                <tr>
                    <td colspan="8">&nbsp;
                    </td>
                </tr>
            }
            else
            {
                if (Model.listaDocumentosAsociados.Count == 0)
                {
                <tr>
                    <td colspan="8">No hay documentos asociados a esta línea de captura.
                    </td>
                </tr>
                }
                else
                {
                    for (int i = 0; i < Model.listaDocumentosAsociados.Count; i++)
                    {                  
                <tr>
                    <td>@Model.listaDocumentosAsociados[i]</td>
                </tr>
                    }
                }
            }
        </tbody>
    </table>
</div>

CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Views/LineaCaptura/_GridLineaCaptura.cshtml
@model Sat.CreditosFiscales.Presentacion.Portal.ViewModels.GeneraLineaCapturaViewModel
@using Sat.CreditosFiscales.Presentacion.Herramientas

<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>


<table id="gridLineaCaptura" class="tabla">
    <tr>
        <th>
            <input type="checkbox" id="chkSeleccionaTodos" name="chkSeleccionaTodos" /></th>
        <th>Línea de captura</th>
        <th></th>
    </tr>
    @if (Model == null || Model.lstLineaCaptura == null)
    {
        <tr>
            <td colspan="3">&nbsp;
            </td>
        </tr>
    }
    else
    {
        if (Model.lstLineaCaptura.Count == 0)
        {
        <tr>
            <td colspan="3">No hay líneas de captura.
            </td>
        </tr>
        }
        else
        {
            using (Html.BeginForm("GenerarArchivos", "LineaCaptura", FormMethod.Post, new { id = "frmLineaCaptura" }))
            {

                for (int i = 0; i < Model.lstLineaCaptura.Count; i++)
                {
        <tr>
            <td>
                <input type="checkbox" value="@Model.lstLineaCaptura[i].Linea" name="chkLineaCaptura" onchange="Valida();"  />
            </td>
            <td>@Model.lstLineaCaptura[i].Linea</td>
            <td><img src="~/Images/doc.gif" alt="Generar pdf" style="cursor:pointer" onclick="GenerarPdf('@Model.lstLineaCaptura[i].Linea')" /></td>
        </tr>
                }
            }
        <tr>
            <td colspan="3">
                <input type="submit" id="btnGenerarDocumentos" value="Generar documentos" /></td>

        </tr>
            
        }
    }
</table>


<script>

    $('#btnGenerarDocumentos').click(function () {
        try {
            var totalSeleccionados = $('#gridLineaCaptura :input:checkbox[name="chkLineaCaptura"]:checked').length;
            if (totalSeleccionados < 1) {
                @Alertas.Errror("Debe seleccionar al menos una línea de captura.", "Aceptar")
            } else {
                $('#frmLineaCaptura').submit();
            }
        } catch (err) {
            alert(err);
        }
    });

    $('#chkSeleccionaTodos').change(function () {
        var seleccion = this.checked;
        $('#gridLineaCaptura :input[type="checkbox"]').each(function () {
            this.checked = seleccion;
        });
    });

    function Valida() {
        var seleccionados = 0;
        var totalCheckBox = $('#gridLineaCaptura :input:checkbox[name="chkLineaCaptura"]').length;
        var totalSeleccionados = $('#gridLineaCaptura :input:checkbox[name="chkLineaCaptura"]:checked').length;
        $('#chkSeleccionaTodos').attr("checked", totalCheckBox == totalSeleccionados)
    }
    function GenerarPdf(lineaCaptura)
    {
        $('#gridLineaCaptura :input:checkbox[name="chkLineaCaptura"]').each(function () {
            var valorCheckBox = this.value;
            if (valorCheckBox == lineaCaptura) {
                this.checked = true;
            }
        });
    }

</script>