CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/ViewModels/CatEsquemasViewModel.cs
using System;
using System.Xml;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Sat.CreditosFiscales.Comunes.Entidades.Catalogos;

namespace Sat.CreditosFiscales.Presentacion.Portal.ViewModels
{

    public class CatEsquemasViewModel
    {
        public List<CatEsquemas> Lista { set; get; }
        public string IdEsquema { set; get; }
        public string Descripcion { set; get; }

    }

    public class CatEsquemasCatalogoViewModel
    {
        public Int16 IdEsquema { set; get; }
        [Required]
        public string Descripcion { set; get; }
        [Required]
        public string Esquema { set; get; }
        public string TargetNamespace { set; get; }
        [Required]
        public int Accion { set; get; }
    }

}

CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/ViewModels/CatReglasViewModel.cs
using System;
using System.Xml;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Sat.CreditosFiscales.Comunes.Entidades.Catalogos;

namespace Sat.CreditosFiscales.Presentacion.Portal.ViewModels
{

    public class CatReglasViewModel
    {
        public List<CatReglas> Lista { set; get; }
        public string IdRegla { set; get; }
        public string Descripcion { set; get; }

    }

    public class CatReglasCatalogoViewModel
    {
        public Guid IdRegla { set; get; }
        [Required]
        public string Descripcion { set; get; }
        [Required]
        public string Regla { set; get; }
        public bool EsValidacion { set; get; }
        [Required]
        public int Accion { set; get; }
    }

}

CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Controllers/CatReglasController.cs
//@(#)CREDITOSFISCALES(W:71950:Sat.CreditosFiscales.Presentacion.Portal.Controllers:Sat.CreditosFiscales.Presentacion.Controllers.Portal.CatReglasController:1:27/08/2013[Assembly:1.0:27/08/2013])

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sat.CreditosFiscales.Presentacion.Herramientas;
using Sat.CreditosFiscales.Presentacion.Portal.ViewModels;
using Sat.CreditosFiscales.Comunes.Entidades.Catalogos;

namespace Sat.CreditosFiscales.Presentacion.Portal.Controllers
{
    public class CatReglasController : Controller
    {


        public ActionResult CatReglas()
        {
            return View("../ReglasEquivalencia/CatReglas");
        }

        private List<CatReglas> ListaCatReglas(string idRegla, string descripcion = "")
        {
            List<CatReglas> lista = new List<CatReglas>();
            using (ClienteServicioCatalogos servicio = new ClienteServicioCatalogos())
            {
                lista = servicio.CreateChannel().ListaCatReglas(idRegla, descripcion);
            }
            return lista;
        }


        public ActionResult Buscar(string IdRegla = "", string Descripcion = "")
        {
            CatReglasViewModel model = new CatReglasViewModel();
            try
            {
                bool esValido = true;
                if (!string.IsNullOrEmpty(IdRegla))
                { 
                    esValido =  IsGuid(IdRegla);
                    if(!esValido)
                        ModelState.AddModelError("IdRegla", "(*) Formato incorrecto");
                }

                if (esValido)
                {
                    model.Lista = ListaCatReglas(IdRegla, Descripcion);
                    if (model.Lista.Count == 0)
                    {
                        ViewBag.OnLoadCompleteMessage = Alertas.Informacion("No hay registros para este criterio", "Aceptar");
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.OnLoadCompleteMessage = Alertas.Errror(ex.Message, "Aceptar");
            }

            var tuple = new Tuple<CatReglasViewModel, CatReglasCatalogoViewModel>(model, new CatReglasCatalogoViewModel());
            return View("../ReglasEquivalencia/CatReglas", tuple);
        }

        public ActionResult Editar(string idRegla)
        {
            CatReglasCatalogoViewModel model = new CatReglasCatalogoViewModel();
            try
            {
                List<CatReglas> Lista = ListaCatReglas(idRegla);
                if (Lista.Count > 0)
                {
                    model.Descripcion = Lista[0].Descripcion;
                    model.EsValidacion = Convert.ToBoolean(Lista[0].EsValidacion);
                    model.IdRegla = new Guid(Lista[0].IdRegla.ToString());
                    model.Regla = Lista[0].Regla;
                }
            }
            catch (Exception ex)
            {
                ViewBag.OnLoadCompleteMessage = Alertas.Errror(ex.Message, "Aceptar");
            }
            var tuple = new Tuple<CatReglasViewModel, CatReglasCatalogoViewModel>(new CatReglasViewModel(), model);
            return View("../ReglasEquivalencia/CatReglas", tuple);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Guardar([Bind(Prefix = "Item2")] CatReglasCatalogoViewModel modelCatalogo)
        {
            try
            {
                if (ValidaModelo(modelCatalogo))
                {
                    using (ClienteServicioCatalogos servicio = new ClienteServicioCatalogos())
                    {
                        servicio.CreateChannel().GuardarRegla(
                            (CatReglas.Accion)modelCatalogo.Accion,
                            new CatReglas()
                            {
                                Descripcion = modelCatalogo.Descripcion,
                                EsValidacion = modelCatalogo.EsValidacion,
                                IdRegla = (CatReglas.Accion)modelCatalogo.Accion == Comunes.Entidades.Catalogos.CatReglas.Accion.Guardar ? Guid.NewGuid() : modelCatalogo.IdRegla,
                                Regla = modelCatalogo.Regla
                            });
                    }

                    ViewBag.OnLoadCompleteMessage = Alertas.Informacion("Regla almacenada exitosamente.", "Aceptar");
                    ModelState.Clear();
                }
                else
                {
                    
                    var tuple = new Tuple<CatReglasViewModel, CatReglasCatalogoViewModel>(new CatReglasViewModel(), modelCatalogo);
                    return View("../ReglasEquivalencia/CatReglas", tuple);
                }
            }
            catch (Exception ex)
            {
                ViewBag.OnLoadCompleteMessage = Alertas.Errror(ex.Message, "Aceptar");
            }
            return View("../ReglasEquivalencia/CatReglas");

        }

        public ActionResult Eliminar(Guid idRegla)
        {
            try
            {
                using (ClienteServicioCatalogos servicio = new ClienteServicioCatalogos())
                {
                    servicio.CreateChannel().EliminarRegla(idRegla);
                }
                ViewBag.OnLoadCompleteMessage = Alertas.Informacion("Regla eliminada exitosamente.", "Aceptar");
            }
            catch (Exception ex)
            {
                ViewBag.OnLoadCompleteMessage = Alertas.Errror(ex.Message, "Aceptar");
            }
            return View("../ReglasEquivalencia/CatReglas");
        }


        private bool ValidaModelo(CatReglasCatalogoViewModel model)
        {
            bool EsValido = ModelState.IsValid;
            if (EsValido)
            {
                Comunes.Entidades.Catalogos.CatReglas.Accion accion = (CatReglas.Accion)model.Accion;
                if (accion == Comunes.Entidades.Catalogos.CatReglas.Accion.Actualizar)
                {
                    if (model.IdRegla == Guid.Empty)
                    {
                        ModelState.AddModelError("IdRegla", "(*) Requerido.");
                        EsValido = false;
                    }
                }

                try
                {
                    var doc = new System.Xml.XmlDocument();
                    doc.LoadXml(model.Regla);
                }
                catch
                {
                    ModelState.AddModelError("Regla", "(*) No es un xml válido.");
                    EsValido = false;
                }


            }

            return EsValido;
        }

        private bool IsGuid(string cadena)
        {
            try
            {
                Guid guid = new Guid(cadena);
                return true;
            }
            catch { return false; }
        }
    }
}

CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Controllers/ReglasEquivalenciaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sat.CreditosFiscales.Comunes.Entidades.Catalogos;
using Sat.CreditosFiscales.Presentacion.Herramientas;
using Sat.CreditosFiscales.Presentacion.Portal.ViewModels;

namespace Sat.CreditosFiscales.Presentacion.Portal.Controllers
{
    public class ReglasEquivalenciaController : Controller
    {
        private string nombreCookie = "LCReglasEquivalencia";

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(GeneraAccesoLogViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool accesoValido = false;
                    using (ClienteServicioConsultaEventos log = new ClienteServicioConsultaEventos())
                    {
                        accesoValido = log.CreateChannel().VerificaAcceso(model.Usuario, model.Contraseña);
                    }

                    if (!accesoValido)
                    {
                        ViewBag.OnLoadCompleteMessage = Alertas.Alerta("Acceso no autorizado", "Aceptar");
                    }
                    else
                    {
                        HttpCookie cookie = new HttpCookie(nombreCookie, model.Contraseña);
                        cookie.Expires = DateTime.Now.AddMinutes(20);
                        Response.Cookies.Add(cookie);

                        return RedirectToAction("Consulta");
                    }
                }

            }
            catch (Exception ex)
            {
                ViewBag.OnLoadCompleteMessage = Alertas.Errror(ex.Message, "Aceptar");
            }

            return View();
        }

        public ActionResult Consulta()
        {
            if (!validaCookie())
            {
                return RedirectToAction("Index");
            }

            ReglasEquivalenciaViewModel model = new ReglasEquivalenciaViewModel();
            CargaCatalogos(model);
            return View(model);

        }

        [HttpPost]
        public ActionResult Consulta(ReglasEquivalenciaViewModel model)
        {
            ModelState.Clear();

            switch (model.Accion)
            {
                ///Consulta
                case 1:
                    model.Reglas = this.ConsultaReglas(model.Parametros);
                    break;
                ////Agrega
                case 2:
                    AgregaRegla(model);
                    model.Reglas = this.ConsultaReglas(model.Parametros);
                    break;
                ////Actualiza
                case 3:
                    ActualizaRegla(model);
                    model.Reglas = this.ConsultaReglas(model.Parametros);
                    break;
            }
            CargaCatalogos(model);
            return View(model);
        }

        public ActionResult Conceptos()
        {
            if (!validaCookie())
            {
                return RedirectToAction("Index");
            }
            ConceptoEquivalenciaViewModel model = new ConceptoEquivalenciaViewModel();
            CargaCatalogosParaConceptos(model);
            return View(model);
        }

        [HttpPost]
        public ActionResult Conceptos(ConceptoEquivalenciaViewModel model)
        {
            ModelState.Clear();

            switch (model.Accion)
            {
                ///Consulta
                case 1:
                    model.Conceptos = this.ConsultaConceptos(model.Parametros);
                    break;
                ////Agrega
                case 2:
                    AgregaConcepto(model);
                    model.Conceptos = this.ConsultaConceptos(model.Parametros);
                    break;
                ////Actualiza
                case 3:
                    ActualizaConcepto(model);
                    model.Conceptos = this.ConsultaConceptos(model.Parametros);
                    break;
            }
            CargaCatalogosParaConceptos(model);
            return View(model);
        }

        private bool validaCookie()
        {
            HttpCookie cookie = Request.Cookies[nombreCookie];
            return (cookie != null);
        }

        private void AgregaRegla(ReglasEquivalenciaViewModel model)
        {
            try
            {
                using (ClienteServicioReglasEquivalencia cliente = new ClienteServicioReglasEquivalencia())
                {
                    cliente.CreateChannel().AgregaRegla(model.Regla);
                }
                model.Parametros.IdAplicacion = model.Regla.IdAplicacion;
                model.Parametros.IdTipoDocumento = model.Regla.IdTipoDocumento;
                model.Parametros.IdTipoObjeto = model.Regla.IdTipoObjeto;
                model.Parametros.ValorObjeto = model.Regla.ValorObjeto;
            }
            catch (Exception ex)
            {
                model.Regla.Excepcion = ex.Message;
            }
        }

        private void AgregaConcepto(ConceptoEquivalenciaViewModel model)
        {
            using (ClienteServicioReglasEquivalencia cliente = new ClienteServicioReglasEquivalencia())
            {
                cliente.CreateChannel().AgregaConcepto(model.Concepto);
            }
            model.Parametros.IdAplicacion = model.Concepto.IdAplicacion;
            model.Parametros.ConceptoDyP = model.Concepto.ConceptoDyP;
            model.Parametros.ConceptoOrigen = model.Concepto.ConceptoOrigen;
            
        }

        private void ActualizaRegla(ReglasEquivalenciaViewModel model)
        {
            try
            {
                using (ClienteServicioReglasEquivalencia cliente = new ClienteServicioReglasEquivalencia())
                {
                    cliente.CreateChannel().ActualizaRegla(model.Regla);
                }
                model.Parametros.IdAplicacion = model.Regla.IdAplicacion;
                model.Parametros.IdTipoDocumento = model.Regla.IdTipoDocumento;
                model.Parametros.IdTipoObjeto = model.Regla.IdTipoObjeto;
                model.Parametros.ValorObjeto = model.Regla.ValorObjeto;
            }
            catch (Exception ex)
            {
                model.Regla.Excepcion = ex.Message;
            }
            
        }

        private void ActualizaConcepto(ConceptoEquivalenciaViewModel model)
        {
            using (ClienteServicioReglasEquivalencia cliente = new ClienteServicioReglasEquivalencia())
            {
                cliente.CreateChannel().ActualizaConcepto(model.Concepto,model.ConceptoOriginal);
            }
            model.Parametros.IdAplicacion = model.Concepto.IdAplicacion;
            model.Parametros.ConceptoDyP = model.Concepto.ConceptoDyP;
            model.Parametros.ConceptoOrigen = model.Concepto.ConceptoOrigen;

        }

        private static void CargaCatalogos(ReglasEquivalenciaViewModel model)
        {
            using (ClienteServicioReglasEquivalencia cliente = new ClienteServicioReglasEquivalencia())
            {
                var clienteActivo = cliente.CreateChannel();
                model.CatAplicacion = clienteActivo.ObtieneCatAplicacion();
                model.CatTipoDocumento = clienteActivo.ObtieneCatTipoDocumento();
                model.CatTipoObjeto = clienteActivo.ObtieneCatTipoObjeto();
            }
        }

        private static void CargaCatalogosParaConceptos(ConceptoEquivalenciaViewModel model)
        {
            using (ClienteServicioReglasEquivalencia cliente = new ClienteServicioReglasEquivalencia())
            {
                var clienteActivo = cliente.CreateChannel();
                model.CatAplicacion = clienteActivo.ObtieneCatAplicacion();
                model.CatConceptoDyP = clienteActivo.ObtieneCatConceptoDyP();                
            }
        }

        private List<ReglaEquivalencia> ConsultaReglas(ReglaEquivalenciaParametroViewModel parametros)
        {
            using (ClienteServicioReglasEquivalencia cliente = new ClienteServicioReglasEquivalencia())
            {
                return cliente.CreateChannel().ObtieneReglas(parametros.IdAplicacion, parametros.IdTipoDocumento, parametros.IdTipoObjeto, parametros.ValorObjeto);
            }
        }

        private List<ConceptoEquivalencia> ConsultaConceptos(ConceptoEquivalenciaParametroViewModel parametros)
        {
            using (ClienteServicioReglasEquivalencia cliente = new ClienteServicioReglasEquivalencia())
            {
                return cliente.CreateChannel().ObtieneConceptos(parametros.IdAplicacion, parametros.ConceptoOrigen, parametros.ConceptoDyP);
            }
        }
    }
}

CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Views/ReglasEquivalencia/CatReglas.cshtml
@model Tuple<Sat.CreditosFiscales.Presentacion.Portal.ViewModels.CatReglasViewModel, Sat.CreditosFiscales.Presentacion.Portal.ViewModels.CatReglasCatalogoViewModel>

@{
    ViewBag.Title = "Clave de cómputo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Scripts.Render("~/bundles/jquerydt")
@Scripts.Render("~/Scripts/Creditos/jsEventos.js")

@section encabezado
{
    <h1>Catalogo de reglas</h1>
    <div style="text-align: right">
        <a href="@Url.Action("Consulta", "ReglasEquivalencia")">Reglas de equivalencia</a>
        &nbsp;|&nbsp;
        <a href="@Url.Action("Conceptos", "ReglasEquivalencia")">Conceptos Equivalencia</a>
        &nbsp;|&nbsp;
        <a href="@Url.Action("ClaveComputo", "ClaveComputo")">Claves de cómputo</a>
        &nbsp;|&nbsp;
        <a href="@Url.Action("CatEsquemas","CatEsquemas")">Catalogo de esquemas</a>
    </div>
}

<style>
    .tablaEvento {
        text-align: left;
    }

        .tablaEvento tr {
            height: 40px !important;
            border: solid 1px #D8D8D8;
            vertical-align: top;
        }

        .tablaEvento input, select, textarea {
            font-size: 8pt;
            font-family: Arial;
        }
</style>


@using (Ajax.BeginForm("Buscar", "CatReglas", new AjaxOptions { UpdateTargetId = "tblResultado" }))
{
    <table class="tablaEvento" style="width: 50%">
        <tr>
            <td>Id. de regla:&nbsp;
                    @Html.TextBoxFor(tuple => tuple.Item1.IdRegla, new { tabindex = 1, size = 36, maxlength = 36, Name = "IdRegla" })
                    @Html.ValidationMessage("IdRegla")
            </td>
            <td>Descripción:&nbsp;
                    @Html.TextBoxFor(tuple => tuple.Item1.Descripcion, new { tabindex = 2, size = 30, maxlength = 30, Name = "Descripcion" })
            </td>
            <td style="text-align: right; vertical-align: bottom">
                <input type="submit" id="btnBuscar" value="Buscar" />
            </td>
        </tr>
    </table>
}



<p>&nbsp;</p>


@if (Model != null && Model.Item1.Lista != null)
{
    if (Model.Item1.Lista.Count > 0)
    {
    <div id="divResultado" style="overflow-x: scroll;">
        <table id="tblResultado" class="tabla" style="width: 100%">
            <thead>
                <tr>
                    <th>Id Regla</th>
                    <th>Descripción</th>
                    <th>Regla</th>
                    <th>Es validación</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                @for (int i = 0; i < Model.Item1.Lista.Count; i++)
                {
                    <tr>
                        <td>
                            @Html.ActionLink(Model.Item1.Lista[i].IdRegla.ToString(), "Editar", "CatReglas", new { idRegla = Model.Item1.Lista[i].IdRegla.ToString() }, null)
                        </td>
                        <td>@Model.Item1.Lista[i].Descripcion</td>
                        <td><a href="javascript:ocultarReloj();" onclick="VerRegla(this, 'Regla')">Ver ...
                                <div style="display: none">@Model.Item1.Lista[i].Regla</div>
                        </a></td>
                        <td>@Model.Item1.Lista[i].EsValidacion</td>
                        <td>@Html.ActionLink("Eliminar", "Eliminar", "CatReglas", new { idRegla = Model.Item1.Lista[i].IdRegla.ToString() }, null)</td>
                    </tr>
                }
            </tbody>
        </table>
        <table style="width: 100%">
            <tr>
                <td style="text-align: right; vertical-align: bottom">
                    <input type="button" value="Nueva regla" onclick="location.href = 'CatReglas'" />
                </td>
            </tr>
        </table>
        <script>
            function VerRegla(elemento, titulo) {
                $('#modalReglaContenido').empty();
                var xmlString = $(elemento).find('div').html();
                $('#modalReglaContenido').html(xmlString);
                try {
                    $('#modalRegla').dialog({
                        autoOpen: true,
                        modal: true,
                        width: 920,
                        height: 400,
                        title: titulo,
                        resizable: false,
                        buttons: [{
                            text: 'Seleccionar texto',
                            click: function () {
                                $('#modalReglaContenido').selText();
                            }
                        }]
                    });

                } catch (err) {
                    openDialog(err, 1, "Aceptar");
                }
            }
            $(function () {
                $('#tblResultado').dataTable({
                    "iDisplayLength": 5, "bFilter": false, "bSort": false, "bPaginate": true,
                    "bLengthChange": true, "bJQueryUI": false, "sPaginationType": "full_numbers",
                    "aLengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "Todos"]],
                    "oLanguage": {
                        "sProcessing": "Procesando...",
                        "sLengthMenu": "Mostrar _MENU_ registros",
                        "sZeroRecords": "No se encontraron resultados",
                        "sEmptyTable": "Ningún dato disponible en esta tabla",
                        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                        "sInfoPostFix": "",
                        "sSearch": "Buscar:",
                        "sUrl": "",
                        "sInfoThousands": ",",
                        "sLoadingRecords": "Cargando...",
                        "oPaginate": {
                            "sFirst": "Primero",
                            "sLast": "Último",
                            "sNext": "Siguiente",
                            "sPrevious": "Anterior"
                        },
                        "oAria": {
                            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                        }

                    }
                });
            });

        </script>
    </div>
    
    <div id="modalRegla" style="display: none">
        <div id="modalReglaContenido" style="overflow: auto"></div>
    </div>
    }
}
else
{


    using (Html.BeginForm("Guardar", "CatReglas", FormMethod.Post, new { id = "frmGuardar" }))
    {
        if (Model != null && Model.Item2.IdRegla != null && Model.Item2.IdRegla != Guid.Empty)
        {
    <table class="tablaEvento" style="width: 100%">
        <tr>
            <td>Id Regla:</td>
            <td>
                @Html.HiddenFor(tuple => tuple.Item2.Accion, new { id = "Accion", Value = 2 })
                @Html.HiddenFor(tuple => tuple.Item2.IdRegla, new { id = "IdRegla" })
                @Model.Item2.IdRegla<br />
                @Html.ValidationMessage("IdRegla")
            </td>
        </tr>
        <tr>
            <td>Descripción:</td>
            <td>
                @Html.TextAreaFor(tuple => tuple.Item2.Descripcion, new { tabindex = 1, maxlength = 150, cols = 80, rows = 3, id = "Descripcion" })<br />
                @Html.ValidationMessageFor(tuple => tuple.Item2.Descripcion, "(* Requerido)")

            </td>
        </tr>
        <tr>
            <td>Regla:</td>
            <td>
                @Html.TextAreaFor(tuple => tuple.Item2.Regla, new { tabindex = 2, cols = 100, rows = 15, id = "Regla" })<br />
                @Html.ValidationMessageFor(tuple => tuple.Item2.Regla, "(* Requerido)")
                @Html.ValidationMessage("Regla")

            </td>
        </tr>
        <tr>
            <td>Validación:</td>
            <td>
                @Html.CheckBoxFor(tuple => tuple.Item2.EsValidacion, new { tabindex = 3, id = "EsValidacion" })<br />
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center">
                <input type="submit" value="Actualizar" />
                <input type="button" value="Cancelar" onclick="location.href = 'CatReglas'" />
            </td>
        </tr>
    </table>
        }
        else
        {
    <table class="tablaEvento">
        <tr>
            <td>Descripción:</td>
            <td>
                @Html.HiddenFor(tuple => tuple.Item2.Accion, new { id = "Accion", Value = 1 })
                @Html.TextAreaFor(tuple => tuple.Item2.Descripcion, new { tabindex = 1, maxlength = 150, cols = 80, rows = 3, id = "Descripcion" })<br />
                @Html.ValidationMessageFor(tuple => tuple.Item2.Descripcion, "(* Requerido)")

            </td>
        </tr>
        <tr>
            <td>Regla:</td>
            <td>
                @Html.TextAreaFor(tuple => tuple.Item2.Regla, new { tabindex = 2, cols = 100, rows = 15, id = "Regla" })<br />
                @Html.ValidationMessageFor(tuple => tuple.Item2.Regla, "(* Requerido)")
                @Html.ValidationMessage("Regla")
            </td>
        </tr>
        <tr>
            <td>Validación:</td>
            <td>
                @Html.CheckBoxFor(tuple => tuple.Item2.EsValidacion, new { tabindex = 3, id = "EsValidacion" })<br />
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center">
                <input type="submit" value="Guardar" />
                <input type="button" value="Cancelar" onclick="location.href = 'CatReglas'" />
            </td>
        </tr>
    </table>
        }
    }
}

CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Views/ReglasEquivalencia/Index.cshtml
@model Sat.CreditosFiscales.Presentacion.Portal.ViewModels.GeneraAccesoLogViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .tablaEvento {
        text-align: left;
    }

        .tablaEvento tr {
            height: 40px !important;
            border: solid 1px #D8D8D8;
        }

        .tablaEvento input, select {
            font-size: 8pt;
            font-family: Arial;
        }
</style>
@section encabezado
{
<h1>Acceso a reglas de equivalencia</h1>
 }

@using (Html.BeginForm("Index", "ReglasEquivalencia", FormMethod.Post))
{
    
    <table class="tablaEvento" align="center">
        <tr>
            <td>Usuario:</td>
            <td>@Html.TextBoxFor(m => m.Usuario, new { tabindex = 1, maxlength = 15 })
                @Html.ValidationMessageFor(m => m.Usuario, "(*) Requerido")
            </td>
        </tr>
        <tr>
            <td>Contraseña:</td>
            <td>@Html.PasswordFor(m => m.Contraseña, new { tabindex = 2, maxlength = 15 })
                @Html.ValidationMessageFor(m => m.Contraseña, "(*) Requerido")
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center">
                <input type="submit" id="btnEntrar" value="Entrar" />
            </td>
        </tr>
    </table>
    
}