CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Controllers/BusquedaController.cs
//@(#)CREDITOSFISCALES(W:71950:Sat.CreditosFiscales.Presentacion.Controllers:Sat.CreditosFiscales.Presentacion.Controllers.BusquedaController:1:12/07/2013[Assembly:1.0:12/07/2013])

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Runtime.Serialization;
using LN = Sat.CreditosFiscales.Procesamiento.LogicaNegocio;
using Sat.CreditosFiscales.Presentacion.Portal.ViewModels;
using Sat.CreditosFiscales.Presentacion.Herramientas;
using Sat.CreditosFiscales.Comunes.Entidades.Servicios;
using Sat.CreditosFiscales.Comunes.Entidades.GeneraFormato;

namespace Sat.CreditosFiscales.Presentacion.Portal.Controllers
{
    public class BusquedaController : Controller
    {

        #region Index
        public ActionResult Index()
        {

            GenerarBusquedaViewModel model = new GenerarBusquedaViewModel();
            model.listaALR = LN.Catalogos.Catalogo.obtenerCatalogoALR();
            model.listaAutoridad = LN.Catalogos.Catalogo.obtenerCatalogoAutoridad();
            model.FechaDocumento = DateTime.Now.ToString("dd/MM/yyy");
            return View(model);
        }



        [HttpPost]
        public ActionResult Index(GenerarBusquedaViewModel model)
        {
            if (modeloEsValido(model))
            {
                List<DocumentoDeterminante> listaDocumento = new List<DocumentoDeterminante>();
                listaDocumento.Add(new DocumentoDeterminante());

                //List<DocumentoDeterminante> listaDocumento = LN.Servicios.ProxyManagerArca.ObtenerInformacionContribuyentePuro(
                //     model.Rfc, model.DocumentoDeterminante, model.IdAutoridad, model.IdALR, Convert.ToDateTime(model.FechaDocumento)
                //    );

                if (listaDocumento.Count > 0)
                {
                    GenerarDocumentosDeterminanteViewModel modelDocumentos = new GenerarDocumentosDeterminanteViewModel();
                    modelDocumentos.listaDocumentos = listaDocumento;

                    return View("GenerarDocumento", modelDocumentos);
                }
                else
                {
                    ViewBag.OnLoadCompleteMessage = Alertas.Errror("No existen documentos para la información registrada.", "Aceptar");
                }
            }


            model.listaALR = LN.Catalogos.Catalogo.obtenerCatalogoALR();
            model.listaAutoridad = LN.Catalogos.Catalogo.obtenerCatalogoAutoridad();
            return View(model);

        }
        private bool modeloEsValido(GenerarBusquedaViewModel model)
        {
            bool esValido = false;
            esValido = ModelState.IsValid;
            if (!ValidaFecha())
            {
                ModelState.AddModelError("FechaDocumento", string.Empty);
                esValido = false;
            }
            return esValido;
        }
        private bool ValidaFecha()
        {
            return true;
        }
        #endregion

        #region Generar Documento
        //public void GuardarDocumento(GenerarBusquedaViewModel model)
        //{
        //    int idSolicitud = 0;
        //    new LN.GeneraFormato.GeneraFormato().GuardaSolicitud(doc);
        //    RedirectToAction("LineaCaptura", new { @idSolicitud = idSolicitud });
        //}

        #endregion
    }
}

CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Views/Busqueda/GenerarDocumento.cshtml
@model Sat.CreditosFiscales.Presentacion.Portal.ViewModels.GenerarDocumentosDeterminanteViewModel
@using Sat.CreditosFiscales.Presentacion.Herramientas

@{
    ViewBag.Title = "Solicitud de generación de formatos de pag";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section encabezado
{
    <h1>Solicitud de genaración de formatos de pago</h1>
}


<table id="gridDocumentos" class="tabla">
    <tr>
        <th style="width: 50px;">Selección de adeudos</th>
        <th style="width: 130px;">Número de resolución determinante</th>
        <th style="width: 100px;">Fecha resolución determinante</th>
        <th style="width: 200px;">Unidad administrativa determinante</th>
        <th style="width: 50px;">Importe histórico</th>
        <th style="width: 50px;">Importe actualizado</th>
        <th style="width: 200px;">Observaciones</th>
    </tr>
    @if (Model == null || Model.listaDocumentos == null)
    {
        <tr>
            <td colspan="8">&nbsp;
            </td>
        </tr>
    }
    else
    {
        if (Model.listaDocumentos.Count == 0)
        {
        <tr>
            <td colspan="8" style="font-size: small">No hay adeudos.
            </td>
        </tr>
        }
        else
        {
            using (Html.BeginForm("GuardarDocumento", "Busqueda", FormMethod.Post, new { id = "frmDocumento" }))
            {

                for (int i = 0; i < Model.listaDocumentos.Count; i++)
                {
                    @Html.Hidden("NumDocumento", Model.listaDocumentos[i].NumDocumento);
                    @Html.Hidden("FechaDocumento", Model.listaDocumentos[i].FechaDocumento);
                    @Html.Hidden("Autoridad", Model.listaDocumentos[i].Autoridad);
                    @Html.Hidden("ImporteHistorico", Model.listaDocumentos[i].ImporteHistorico);
                    @Html.Hidden("ImporteActualizacion", Model.listaDocumentos[i].ImporteActualizacion);
                    @Html.Hidden("Observaciones", Model.listaDocumentos[i].Observaciones);
        <tr>
            <td>
                <input type="checkbox" value="@Model.listaDocumentos[i].NumDocumento" name="chkDocumento" />
            </td>
            <td>@Model.listaDocumentos[i].NumDocumento</td>
            <td>@Model.listaDocumentos[i].FechaDocumento</td>
            <td>@Model.listaDocumentos[i].Autoridad</td>
            <td>@Model.listaDocumentos[i].ImporteHistorico</td>
            <td>@Model.listaDocumentos[i].ImporteActualizacion</td>
            <td>@Model.listaDocumentos[i].Observaciones</td>
        </tr>
                }


            }
        }

    }


</table>

@section botonera
{
    <input type="submit" id="btnSiguiente" value="Siguiente" />
}


@section mensajeContribuyente
{

}

<script>
    $(document).ready(function () {
        $('#btnSiguiente').click(function () {
            try {
                var totalSeleccionados = $('#gridDocumentos :input:checkbox[name="chkDocumento"]:checked').length;
                if (totalSeleccionados < 1) {
                    @Alertas.Errror("Debe seleccionar al menos un documento.", "Aceptar")
                    return false;
                } else {
                    //$('#frmLineaCaptura').submit();
                }
            } catch (err) {
                alert(err);
            }
        });
    });
</script>

CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Views/Busqueda/Index.cshtml
@model Sat.CreditosFiscales.Presentacion.Portal.ViewModels.GenerarBusquedaViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .tabla_Busqueda {
        text-align: left;
        width: 80%;
    }

        .tabla_Busqueda input {
            font-size: 8pt;
            font-family: Arial;
        }

        .tabla_Busqueda select {
            font-family: Arial;
            font-size: 8pt;
            width: 300px;
        }
</style>


@section encabezado
{
    <h1>Búsqueda</h1>
}

Para generar el formato para pago de una resolución determinante a su cargo, favor de ingresar los siguientes datos, tal y como aparecen en los documentos proporcionados por el SAT.


@using (Ajax.BeginForm("Index", "Busqueda", new AjaxOptions { UpdateTargetId = "result" }))
{
    
    <table class="tabla_Busqueda">
        <tr>
            <td>Registro federal de contribuyentes</td>
            <td>@Html.TextBoxFor(m => m.Rfc, new { tabindex = 1 })
                @Html.ValidationMessageFor(m => m.Rfc, "(* Requerido)")</td>

        </tr>
        <tr>
            <td>Documento determinante</td>
            <td>@Html.TextBoxFor(m => m.DocumentoDeterminante, new { tabindex = 2 })
                @Html.ValidationMessageFor(m => m.DocumentoDeterminante, "(* Requerido)")</td>

        </tr>
        <tr>
            <td>Fecha del documento</td>
            <td>
                @Html.TextBoxFor(m => m.FechaDocumento, new { tabindex = 3, maxlength = 10, @class = "tcal", onKeyPress = "return valFecha(event);", onpaste = "return false;" })
                @Html.ValidationMessageFor(m => m.FechaDocumento, "(* Es necesario capturar una fecha válida)")

            </td>

        </tr>
        <tr>
            <td>Autoridad</td>
            <td>
                @Html.DropDownListFor(m => m.IdAutoridad, new SelectList(Model.listaAutoridad, "IdAutoridad", "Descripcion"), new { tabindex = 4, id = "cmbAutoridades" })
            </td>
        </tr>
        <tr>
            <td>ALR que controla el adeudo</td>
            <td>
                @Html.DropDownListFor(m => m.IdALR, new SelectList(Model.listaALR, "IdAlr", "Descripcion"), new { tabindex = 5, id = "cmbALRs" })

            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" value="Buscar documento" id="btnBuscar" />
            </td>
            <td>
                <input type="reset" value="Limpiar campos" id="btnReset" />
            </td>
        </tr>
    </table>
}


@section botonera
{

}

@section mensajeContribuyente
{

}