CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Controllers/GeneraArchivoController.cs
//@(#)CREDITOSFISCALES(W:71950:Sat.CreditosFiscales.Presentacion.Controllers:Sat.CreditosFiscales.Presentacion.Controllers.GeneraArchivoController:1:12/07/2013[Assembly:1.0:12/07/2013])

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using System.Web;
using System.Web.Mvc;
using Sat.CreditosFiscales.Procesamiento.LogicaNegocio.Servicios;
using Sat.CreditosFiscales.Presentacion.Herramientas;
using Sat.CreditosFiscales.Comunes.Entidades.AccesoLogEventos;
using Sat.CreditosFiscales.Comunes.Entidades.CodigosError;

namespace Sat.CreditosFiscales.Presentacion.Portal.Controllers
{
    public class GeneraArchivoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GeneraArchivoPdf(string folios)
        {
            try
            {
                List<string> listaDeFolios = folios.Split(',').ToList();
                byte[] archivoDeBytes = GeneraArchivoDeBytes(listaDeFolios);
                MemoryStream ms = new MemoryStream();
                ms.Write(archivoDeBytes, 0, archivoDeBytes.Length);
                ms.Position = 0;
                return File(ms, "application/pdf");
            }
            catch (ExcepcionTipificada ex)
            {
                ViewBag.OnLoadCompleteMessage = Alertas.Errror(ex.Mensaje, "Aceptar");
            }
            catch (Exception ex)
            {
                string ticket = AccesoLogEventos.EscribirEntradaLog((int)EnumErroresLineaCaptura.ErrorAlGenerarArhivo, ex);
                ExcepcionTipificada exTip = new ExcepcionTipificada("No se logró generar el archivo para las líneas de captura.", ex, ticket);
                ViewBag.OnLoadCompleteMessage = exTip.Mensaje;
            }
            return View("Blank");
        }


        private byte[] GeneraArchivoDeBytes(List<string> listaDeFolios)
        {
            using (ClienteServicioLineaCaptura servicio = new ClienteServicioLineaCaptura())
            {
                return servicio.CreateChannel().GeneraArchivos(listaDeFolios);
            }
        }
    }
}

CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Views/GeneraArchivo/Blank.cshtml
@{
    ViewBag.Title = "Blank";
    Layout = null;
}



<script type="text/javascript">
    var mensaje = '@MvcHtmlString.Create(ViewBag.OnLoadCompleteMessage)'
    var iframe = parent.document.getElementById('iframePdf');
    iframe.width = 0;
    iframe.height = 0;
    parent.openDialog(mensaje,1,"Aceptar");
</script>

CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Views/GeneraArchivo/GeneraArchivo.cshtml
@model byte[]
@{
    Layout = null;
}
@{
    var archivopdf = "LC" + DateTime.Now.ToString("yyyyMMddHHmmss") + ".pdf";
    Response.AddHeader("content-length", Model.Length.ToString());
    Response.AddHeader("content-disposition", "attachment; filename=" + archivopdf);
    Response.ContentType = "Application/pdf";
    Response.WriteBinary(Model);
    
}

CreditosFiscales/Fuentes/RCOBRANZA_ADEUDOS/Presentacion/Sat.CreditosFiscales.Presentacion.Portal/Views/GeneraArchivo/Index.cshtml
<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section encabezado
{
    <h1>Formato para pago</h1>
}

@{
    var listaDeFolios = Request.QueryString["folios"];
    var vieneDePaginaDeudorPuro = string.IsNullOrEmpty(Request.QueryString["deudorPuro"]) ? true : Convert.ToBoolean(Request.QueryString["deudorPuro"]);   
}

<iframe id="iframePdf" src="@Url.Action("GeneraArchivoPdf", "GeneraArchivo", new { folios = listaDeFolios })" width="650" height="650" style="border:none"></iframe>

<div id="botonera">
    @if (vieneDePaginaDeudorPuro)
    {
        <input type="button" value="Regresar a consulta" onclick="reloj();window.location.href='@Url.Action("DeudoresPuros", "GeneracionPrivada")    ';" />
    }
    else
    {
        <input type="button" value="Regresar a pago total" onclick="reloj();window.location.href='@Url.Action("Index", "GeneracionPrivada", new { accion = Sat.CreditosFiscales.Comunes.Entidades.AccionesPantalla.EnumAccionGeneraFormato.PagoTotal })    ';" />
    }
</div>